config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :guests
  resources :rooms
	root 'rooms#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
	validates :name, case_sensitive: false, uniqueness: true, presence: true

	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create },
										presence: true, uniqueness: true, case_sensitive: false
	validates :room_id, presence: true, numericality: { only_integer: true}

	belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
	validates :name, case_sensitive: false, uniqueness: true, presence: true

	validates :address, presence: true, uniqueness: true, case_sensitive: false

	validates :capacity, presence: true, numericality: { greater_than: 0}

	has_many :guests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_action :authenticate_user!
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)
		@room = Room.find_by_id(@guest.room_id)

		if @room
			if @room.guests.size >= @room.capacity
				flash[:notice] = "room capacity not enough"	
				render 'new'
				
			else
				if @guest.save
					flash[:notice] = "guest successfully create"
					redirect_to @guest
				else
					render 'new'
				end
			end

		else
			if @guest.room_id < 0 and @guest.save
				flash[:notice] = "guest successfully create"
				redirect_to @guest
			else
				flash[:notice] = "cannot find the room"
				render 'new'
			end
		end

    #respond_to do |format|
      #if @guest.save 
       # format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        #format.json { render :show, status: :created, location: @guest }
      #else
       # format.html { render :new }
        #format.json { render json: @guest.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
		@helper = Guest.new(guest_params)
		@room = Room.find_by_id(@helper.room_id)

		if @room
			if @room.guests.size >= @room.capacity
				flash[:notice] = "room capacity not enough"
				render 'edit'
			else
				if @guest.update(guest_params)
					flash[:notice] = "guest info successfully update"
					redirect_to @guest
				else
					render 'edit'
				end
			end
			
		else
			if @helper.room_id < 0 and @guest.update(guest_params)
				flash[:notice] = "guest info successfully update"
				redirect_to @guest
			else
				flash[:notice] = "cannot find the room"
				render 'edit'
			end
		end
    #respond_to do |format|
      #if @guest.update(guest_params)
        #format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        #format.json { render :show, status: :ok, location: @guest }
      #else
        #format.html { render :edit }
        #format.json { render json: @guest.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:name, :email, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_edit_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
		#@room.guests.update(@room.guests.id, room_id = -1)
		@room.guests.each do |guest|
			guest.update(room_id: -1)
		end
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :address, :capacity)
    end

		def room_edit_params
			params.require(:room).permit(:name, :address)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.number_field :room_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>
<p id="notice"><%= flash[:notice] %></p>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.email %></td>
        <td><%= guest.room_id %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>
<br>
<%= link_to 'room entry', rooms_path%>

app/views/guests/new.html.erb
<h1>New Guest</h1>
<p id="notice"><%= flash[:notice] %></p>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>


<h2>Room Info</h2>
<% if (@guest.room_id > 0) %>
	<p>
		<strong> name:</strong>
		<%= @guest.room.name %>
	</p>

	<p>
		<strong> address:</strong>
		<%= @guest.room.address %>
	</p>
	<p>
		<strong> number: </strong>
		<%= @guest.room.id %>
	</p>
<% else %>
	<p>
		no room assigned
	</p>
<% end %>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firsttry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= form_for :room, url: room_path(@room), method: :patch do |f| %>
 
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@room.errors.count, "error") %> prohibited
        this room from being saved:
      </h2>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Capacity</th>
			<th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.address %></td>
        <td><%= room.capacity %></td>
				<td><%= room.id %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>
<br>
<%= link_to 'guest entry', guests_path %>
<br>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @room.address %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<h2>Guest</h2>
<% @room.guests.each do |guest| %>
	<p>
		<strong>Name:</strong>
		<%= guest.name %>
	</p>
	<p>
		<strong>Email:</strong>
		<%= guest.email %>
	</p>
<% end %>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>